### ISSUE TITLE
Добавить базовую структуру базы данных для модуля Library

### ISSUE THREAD

**Issue by Mikhail-Golovai** [DDM-Group/Library#1]
Необходимо описать базовую структуру данных для информационного модуля.
Для начала достаточно описать модель информационного материала. Т.к. категории информации будут различными, сами данные решено хранить в JSON

**Comment by Trostnick** [comment]
Создан пустой проект, добавлена интеграция с git, добавлена ветка dev, первый коммит залит в репозиторий

**Comment by Trostnick** [comment]
[скрипт для библиотеки.txt](https://github.com/DDM-Group/Library/files/4110068/default.txt)

Скрипт, по которому создаётся текущая версия бд для модуля Library

**Comment by Trostnick** [comment]
![LibraryDbScheme](https://user-images.githubusercontent.com/22326960/73094702-3460fa80-3ef2-11ea-8435-8d25a0ed2401.jpg)
